apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-db2
  namespace: sut
spec:
  replicas: 1
  selector:
    matchLabels:
      key: pod-db2
  template:
    metadata:
      labels:
        key: pod-db2
    spec:
      volumes:
      - name: db2-volume
        emptyDir: {}
      containers:
        - name: db
          image: localhost:32000/sut/db2
          ports:
            - containerPort: 50000
          env:
            - name: "LICENSE"
              value: "accept"
            - name: "DB2INST1_PASSWORD"
              value: "admin123"
            - name: "DBNAME"
              value: "sutdb"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /database
              name: db2-volume
