apiVersion: v1
kind: Service
metadata:
  name: service-db2-session
  namespace: sut
spec:  
  type: ClusterIP
  selector:
    key: pod-db2
  ports:
    - name: host
      protocol: TCP      
      port: 48100
      targetPort: 50000
