
-- https://www.ibm.com/support/producthub/iias/docs/content/SSHRBY/com.ibm.swg.im.dashdb.sql.rtn.doc/doc/r0056510.html
-- Per minute query
-- Per week retention
SELECT
	APPLICATION_HANDLE,
	APPLICATION_NAME,
	TOTAL_APP_COMMITS,
	TOTAL_APP_ROLLBACKS,
	ACT_COMPLETED_TOTAL,
	APP_RQSTS_COMPLETED_TOTAL, 
	AVG_RQST_CPU_TIME,
	ROUTINE_TIME_RQST_PERCENT,
	RQST_WAIT_TIME_PERCENT,
	ACT_WAIT_TIME_PERCENT,
	IO_WAIT_TIME_PERCENT,
	LOCK_WAIT_TIME_PERCENT,
	AGENT_WAIT_TIME_PERCENT,
	NETWORK_WAIT_TIME_PERCENT,
	SECTION_PROC_TIME_PERCENT,
	SECTION_SORT_PROC_TIME_PERCENT,
	COMPILE_PROC_TIME_PERCENT,
	TRANSACT_END_PROC_TIME_PERCENT,
	UTILS_PROC_TIME_PERCENT,
	AVG_LOCK_WAITS_PER_ACT,
	AVG_LOCK_TIMEOUTS_PER_ACT,
	AVG_DEADLOCKS_PER_ACT,
	AVG_LOCK_ESCALS_PER_ACT,
	ROWS_READ_PER_ROWS_RETURNED,
FROM
	SYSIBMADM.MON_CONNECTION_SUMMARY


-- validate load balance
-- https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.sql.rtn.doc/doc/r0053938.html
-- per 5 minutes
-- 1 week retention


SELECT
	APPLICATION_HANDLE,
	APPLICATION_NAME,
	POOL_DATA_L_READS,
	POOL_INDEX_L_READS,
	POOL_DATA_P_READS,
	POOL_INDEX_P_READS,
	POOL_DATA_WRITES,
	POOL_INDEX_WRITES,
	DIRECT_READS,
	DIRECT_WRITES,
	DIRECT_READ_REQS,
	DIRECT_WRITE_REQS,
	ROWS_MODIFIED,
	ROWS_READ,
	ROWS_RETURNED
FROM TABLE(MON_GET_CONNECTION(cast(NULL as bigint), -2)) AS t;




-- validate locks
-- https://www.ibm.com/support/knowledgecenter/SSHRBY/com.ibm.swg.im.dashdb.sql.rtn.doc/doc/r0056601.html
-- per 1 minutes
-- 1 week retention

SELECT
	LOCK_NAME,
	LOCK_WAIT_ELAPSED_TIME,
	TABSCHEMA,
	TABNAME,
	DATA_PARTITION_ID,
	LOCK_MODE,
	LOCK_CURRENT_MODE,
	LOCK_MODE_REQUESTED,
	REQ_APPLICATION_HANDLE,
	REQ_AGENT_TID,
	REQ_MEMBER,
	REQ_USERID,
	SUBSTR(REQ_STMT_TEXT, 1, 30),
	HLD_APPLICATION_HANDLE,
	HLD_MEMBER,
	SUBSTR(HLD_CURRENT_STMT_TEXT, 1, 30)
FROM
	SYSIBMADM.MON_LOCKWAITS;
