CREATE SCHEMA "SUTSCHEMA";
CREATE TABLESPACE STORAGES MANAGED BY AUTOMATIC STORAGE;
CREATE TABLESPACE INDEXES MANAGED BY AUTOMATIC STORAGE;

CREATE TABLE "SUTSCHEMA   "."SPRING_SESSION"  (
        "SESSION_ID" CHAR(36 OCTETS) NOT NULL ,
        "CREATION_TIME" BIGINT NOT NULL ,
        "LAST_ACCESS_TIME" BIGINT NOT NULL ,
        "MAX_INACTIVE_INTERVAL" INTEGER NOT NULL ,
        "PRINCIPAL_NAME" VARCHAR(100 OCTETS) )
        IN "STORAGES" INDEX IN "INDEXES" ORGANIZE BY ROW;

ALTER TABLE "SUTSCHEMA"."SPRING_SESSION" ADD CONSTRAINT "SPRING_SESSION_PK" PRIMARY KEY ("SESSION_ID");

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "SUTSCHEMA"."SPRING_SESSION_IX1" ON "SUTSCHEMA"."SPRING_SESSION" ("LAST_ACCESS_TIME" ASC)
        COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "SUTSCHEMA"."SPRING_SESSION_IX2" ON "SUTSCHEMA"."SPRING_SESSION" ("PRINCIPAL_NAME" ASC)
    COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE TABLE "SUTSCHEMA"."SPRING_SESSION_ATTRIBUTES"  (
        "SESSION_ID" CHAR(36 OCTETS) NOT NULL ,
        "ATTRIBUTE_NAME" VARCHAR(200 OCTETS) NOT NULL ,
        "ATTRIBUTE_BYTES" BLOB(1048576) LOGGED NOT COMPACT NOT NULL )
        IN "STORAGES" INDEX IN "INDEXES" ORGANIZE BY ROW;

ALTER TABLE "SUTSCHEMA"."SPRING_SESSION_ATTRIBUTES"
    ADD CONSTRAINT "SPRING_SESSION_ATTRIBUTES_PK" PRIMARY KEY ("SESSION_ID", "ATTRIBUTE_NAME");



